# Generated by Django 4.1.2 on 2022-11-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_director_remove_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='director_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
