# Generated by Django 4.1.2 on 2022-11-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_director_director_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='director_email',
            field=models.EmailField(default='Zalupa@s.gorы', max_length=254),
        ),
    ]
