# Generated by Django 4.1.2 on 2022-11-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_alter_director_director_email'),
        ('movie_app', '0011_alter_movie_director'),
    ]

    operations = [
    ]
