# Generated by Django 4.1.2 on 2022-11-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_merge_20221116_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
