# Generated by Django 4.1.2 on 2022-11-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0021_actor_director_slug_movie_director_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(null=True, to='movie_app.actor'),
        ),
    ]
